<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-24T11:27:50 IST" name="Suite" finished-at="2022-05-24T11:28:29 IST" duration-ms="39343">
    <groups>
      <group name="sanity">
        <method signature="CreateContactTest.createContactTest()[pri:0, instance:com.vtiger.contactTest.CreateContactTest@7772054c]" name="createContactTest" class="com.vtiger.contactTest.CreateContactTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2022-05-24T11:27:50 IST" name="Test" finished-at="2022-05-24T11:28:29 IST" duration-ms="39343">
      <class name="com.vtiger.contactTest.CreateContactTest">
        <test-method is-config="true" signature="beforesuite()[pri:0, instance:com.vtiger.contactTest.CreateContactTest@7772054c]" started-at="2022-05-24T11:27:47 IST" name="beforesuite" finished-at="2022-05-24T11:27:50 IST" duration-ms="2589" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforesuite -->
        <test-method is-config="true" signature="beforeclass(java.lang.String)[pri:0, instance:com.vtiger.contactTest.CreateContactTest@7772054c]" started-at="2022-05-24T11:27:51 IST" name="beforeclass" finished-at="2022-05-24T11:28:10 IST" duration-ms="18478" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method is-config="true" signature="beforemethod()[pri:0, instance:com.vtiger.contactTest.CreateContactTest@7772054c]" started-at="2022-05-24T11:28:10 IST" name="beforemethod" finished-at="2022-05-24T11:28:12 IST" duration-ms="2875" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method signature="createContactTest()[pri:0, instance:com.vtiger.contactTest.CreateContactTest@7772054c]" started-at="2022-05-24T11:28:13 IST" name="createContactTest" finished-at="2022-05-24T11:28:26 IST" duration-ms="13127" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.vtiger.contactTest.CreateContactTest.createContactTest(CreateContactTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="aftermethod()[pri:0, instance:com.vtiger.contactTest.CreateContactTest@7772054c]" started-at="2022-05-24T11:28:26 IST" name="aftermethod" finished-at="2022-05-24T11:28:28 IST" duration-ms="1427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method is-config="true" signature="afterclass()[pri:0, instance:com.vtiger.contactTest.CreateContactTest@7772054c]" started-at="2022-05-24T11:28:28 IST" name="afterclass" finished-at="2022-05-24T11:28:29 IST" duration-ms="1515" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterclass -->
        <test-method is-config="true" signature="aftersuite()[pri:0, instance:com.vtiger.contactTest.CreateContactTest@7772054c]" started-at="2022-05-24T11:28:30 IST" name="aftersuite" finished-at="2022-05-24T11:28:30 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftersuite -->
      </class> <!-- com.vtiger.contactTest.CreateContactTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
